# 📊 Lab Work - 2.2

## Q1: Missing Indicator + Random Sample Imputation
## Q2: KNN Imputer (Multivariate Imputation)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

np.random.seed(42)

# 🔹 Q1: Missing Indicator + Random Sample Imputation

## Step 1: Create Dataset with Missing Values

In [2]:
data = {
    'Age': [25, 30, np.nan, 35, np.nan, 40, 28, np.nan],
    'Salary': [50000, 60000, 55000, np.nan, 65000, 70000, np.nan, 62000]
}

df = pd.DataFrame(data)
df

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  35.0      NaN
4   NaN  65000.0
5  40.0  70000.0
6  28.0      NaN
7   NaN  62000.0

## Step 2: Add Missing Indicator Column

In [3]:
df['Age_missing'] = df['Age'].isnull().astype(int)
df

    Age   Salary  Age_missing
0  25.0  50000.0            0
1  30.0  60000.0            0
2   NaN  55000.0            1
3  35.0      NaN            0
4   NaN  65000.0            1
5  40.0  70000.0            0
6  28.0      NaN            0
7   NaN  62000.0            1

## Step 3: Random Sample Imputation

In [4]:
def random_impute(series):
    random_sample = series.dropna().sample(series.isnull().sum(), replace=True)
    random_sample.index = series[series.isnull()].index
    return series.fillna(random_sample)

df_imputed = df.copy()
df_imputed['Age'] = random_impute(df['Age'])
df_imputed

    Age   Salary  Age_missing
0  25.0  50000.0            0
1  30.0  60000.0            0
2  40.0  55000.0            1
3  35.0      NaN            0
4  28.0  65000.0            1
5  40.0  70000.0            0
6  28.0      NaN            0
7  35.0  62000.0            1

## Step 4: Compare Original vs Imputed

In [5]:
print("Original Dataset:\n", df)
print("\nImputed Dataset:\n", df_imputed)

Original Dataset:
     Age   Salary  Age_missing
0  25.0  50000.0            0
1  30.0  60000.0            0
2   NaN  55000.0            1
3  35.0      NaN            0
4   NaN  65000.0            1
5  40.0  70000.0            0
6  28.0      NaN            0
7   NaN  62000.0            1

Imputed Dataset:
     Age   Salary  Age_missing
0  25.0  50000.0            0
1  30.0  60000.0            0
2  40.0  55000.0            1
3  35.0      NaN            0
4  28.0  65000.0            1
5  40.0  70000.0            0
6  28.0      NaN            0
7  35.0  62000.0            1

# 🔹 Q2: KNN Imputer (Multivariate Imputation)

## Step 1: Create Multivariate Dataset

In [6]:
data2 = {
    'Age': [25, np.nan, 35, 40, np.nan, 29, 33, np.nan],
    'Salary': [50000, 60000, np.nan, 80000, 65000, np.nan, 72000, 69000],
    'Experience': [2, 5, 10, np.nan, 7, 3, np.nan, 6]
}

df2 = pd.DataFrame(data2)
df2

    Age   Salary  Experience
0  25.0  50000.0         2.0
1   NaN  60000.0         5.0
2  35.0      NaN        10.0
3  40.0  80000.0         NaN
4   NaN  65000.0         7.0
5  29.0      NaN         3.0
6  33.0  72000.0         NaN
7   NaN  69000.0         6.0

## Step 2: Apply KNN Imputer (k=3)

In [7]:
imputer = KNNImputer(n_neighbors=3)
df2_imputed = pd.DataFrame(imputer.fit_transform(df2), columns=df2.columns)
df2_imputed

         Age        Salary  Experience
0  25.000000  50000.000000    2.000000
1  29.666667  60000.000000    5.000000
2  35.000000  68666.666667   10.000000
3  40.000000  80000.000000    6.333333
4  32.333333  65000.000000    7.000000
5  29.000000  59666.666667    3.000000
6  33.000000  72000.000000    6.333333
7  32.333333  69000.000000    6.000000

## Step 3: Compare Before and After

In [8]:
print("Original Dataset:\n", df2)
print("\nImputed Dataset:\n", df2_imputed)

Original Dataset:
     Age   Salary  Experience
0  25.0  50000.0         2.0
1   NaN  60000.0         5.0
2  35.0      NaN        10.0
3  40.0  80000.0         NaN
4   NaN  65000.0         7.0
5  29.0      NaN         3.0
6  33.0  72000.0         NaN
7   NaN  69000.0         6.0

Imputed Dataset:
          Age        Salary  Experience
0  25.000000  50000.000000    2.000000
1  29.666667  60000.000000    5.000000
2  35.000000  68666.666667   10.000000
3  40.000000  80000.000000    6.333333
4  32.333333  65000.000000    7.000000
5  29.000000  59666.666667    3.000000
6  33.000000  72000.000000    6.333333
7  32.333333  69000.000000    6.000000

## Step 4: Experiment with Different K Values

In [9]:
for k in [2, 3, 5]:
    imputer = KNNImputer(n_neighbors=k)
    temp = pd.DataFrame(imputer.fit_transform(df2), columns=df2.columns)
    print(f"\nK = {k}\n", temp)

K = 2
     Age   Salary  Experience
0  25.0  50000.0         2.0
1  32.0  60000.0         5.0
2  35.0  68500.0        10.0
3  40.0  80000.0         6.5
4  32.0  65000.0         7.0
5  29.0  55000.0         3.0
6  33.0  72000.0         6.5
7  32.0  69000.0         6.0

K = 3
          Age        Salary  Experience
0  25.000000  50000.000000    2.000000
1  29.666667  60000.000000    5.000000
2  35.000000  68666.666667   10.000000
3  40.000000  80000.000000    6.333333
4  32.333333  65000.000000    7.000000
5  29.000000  59666.666667    3.000000
6  33.000000  72000.000000    6.333333
7  32.333333  69000.000000    6.000000

K = 5
     Age   Salary  Experience
0  25.0  50000.0         2.0
1  32.4  60000.0         5.0
2  35.0  69200.0        10.0
3  40.0  80000.0         6.2
4  32.4  65000.0         7.0
5  29.0  63200.0         3.0
6  33.0  72000.0         6.2
7  32.4  69000.0         6.0