# 📊 Lab Work - 3.3

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Binarizer, KBinsDiscretizer
np.random.seed(42)

# 🔹 Q1: Binning (Discretization)
### Convert continuous age into categories

In [2]:
# Create Age column
ages = np.random.randint(18, 71, 100)
df_age = pd.DataFrame({'Age': ages})

# Define bins
bins = [18, 30, 50, 70]
labels = ['Young', 'Middle', 'Senior']

# Apply binning
df_age['Age_Group'] = pd.cut(df_age['Age'], bins=bins, labels=labels, right=True)

# Count values
counts = df_age['Age_Group'].value_counts()

df_age.head(), counts

(   Age Age_Group
 0   56    Senior
 1   69    Senior
 2   46    Middle
 3   32    Middle
 4   60    Senior,
 Age_Group
 Middle    41
 Senior    38
 Young     21
 Name: count, dtype: int64)

# 🔹 Q2: Binarization
### Convert income into 0/1 based on threshold

In [3]:
# Create Income data
income = np.random.randint(20000, 100001, 100)
df_income = pd.DataFrame({'Income': income})

# Apply Binarizer
binarizer = Binarizer(threshold=50000)
df_income['Income_Binary'] = binarizer.fit_transform(df_income[['Income']])

df_income.head()

   Income  Income_Binary
0   59099              1
1   28571              0
2   58044              1
3   71214              1
4   81228              1

# 🔹 Q3: Quantile Binning
### Split salary into equal-sized groups

In [4]:
# Skewed salary data
salary = np.random.exponential(scale=50000, size=100)
df_salary = pd.DataFrame({'Salary': salary})

# Quantile binning
kbins_q = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='quantile')
df_salary['Quantile_Bin'] = kbins_q.fit_transform(df_salary[['Salary']])

# First 10 rows
df_salary.head(10)

c:\Users\Dell\AppData\Local\Python\pythoncore-3.10-64\lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

         Salary  Quantile_Bin
0  50304.118242           2.0
1  57082.062643           2.0
2  37850.651953           1.0
3  29690.724602           1.0
4  40247.876931           1.0
5  44909.861043           2.0
6   4215.478399           0.0
7  23074.356376           1.0
8  13864.145798           0.0
9  81263.061263           2.0

In [5]:
# Distribution count
df_salary['Quantile_Bin'].value_counts()

Quantile_Bin
2.0    25
1.0    25
0.0    25
3.0    25
Name: count, dtype: int64

# 🔹 Q4: K-Means Binning
### Cluster-based binning

In [6]:
# Spending Score
spending = np.random.randint(1, 101, 100)
df_spend = pd.DataFrame({'SpendingScore': spending})

# KMeans binning
kbins_k = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='kmeans')
df_spend['KMeans_Bin'] = kbins_k.fit_transform(df_spend[['SpendingScore']])

df_spend.head()

   SpendingScore  KMeans_Bin
0             85         2.0
1             32         0.0
2             87         2.0
3             33         0.0
4             67         1.0

In [7]:
# Compare with quantile
kbins_q2 = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
df_spend['Quantile_Bin'] = kbins_q2.fit_transform(df_spend[['SpendingScore']])

df_spend.head()

c:\Users\Dell\AppData\Local\Python\pythoncore-3.10-64\lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

   SpendingScore  KMeans_Bin  Quantile_Bin
0             85         2.0           2.0
1             32         0.0           1.0
2             87         2.0           2.0
3             33         0.0           1.0
4             67         1.0           2.0